spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:h2:mem:myTestDb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  routing:
    key: tasksRouting
  exchange:
    name: tasksExchange

user:
  tasksResponse:
    queue: getUserTasksResponse
  existence:
    queue: userExistence
    response:
      queue: userExistenceResponse
  tasks:
    queue: getUserTasks
    response:
      queue: getUserTasksResponse
    routingKey: getUserTasksRoutingKey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
